### ISSUE TITLE
Useless if statement in spline shader code

### ISSUE THREAD

**Issue by siliotar** [jacobsjo/snowcapped#10]
https://github.com/jacobsjo/snowcapped/blob/4ce7d2e1d3879b495111d331dca68b3fe83a0b2f/src/main/Visualization/Shader/Spline.glsl#L12

'wi' may be uninitialized or ranged from 0 to num_weirnesses.

**Comment by siliotar** [comment]
I think it should be:
`if (wi == 0)`

**Comment by jacobsjo** [comment]
No, I think it should be `if (wi < 0)` but `wi` should be initalized as `-1`

Either way, I think I am going to deprecated this shader map code soon anyways as it is probably impossible to make work with density functions - and it is causing a bit too many issues for a lot of people. So I'll close this as 'wont fix'.

**Comment by jacobsjo** [comment]
fixed in #12
