### ISSUE TITLE
Hillshade not functioning properly

### ISSUE THREAD

**Issue by ApolloDatapacks** [jacobsjo/snowcapped#11]
[tectonic-indev.snowcapped.zip](https://github.com/jacobsjo/snowcapped/files/9945032/tectonic-indev.snowcapped.zip)
![image](https://user-images.githubusercontent.com/102649729/200150900-5f29c240-751e-412d-9e70-49355281b53e.png)

**Comment by ApolloDatapacks** [comment]
Also, it's not an issue with a high amount of continentalness/erosion intervals. Here's a version of the pack above but with the offset spline grid only being 7x7 at the same issue occuring: 
[tectonic-indev-2.zip](https://github.com/jacobsjo/snowcapped/files/9945040/tectonic-indev-2.zip)

**Comment by jacobsjo** [comment]
fixed in #12
