### ISSUE TITLE
allow importing of non snow capped files

### ISSUE THREAD

**Issue by Danjhop4** [jacobsjo/snowcapped#21]
I want to run my datapack noise though the site but it was made using a different tool

**Comment by jacobsjo** [comment]
Importing biome configurations (dimension files) is not possible as there is no way to know how to split it into layouts, slices etc.

If you want to make a new biome configuration but want to use custom noises and density functions, go to the settings menu and import the datapack containing those.

If you simply want to see how your biome layout generates, go to [https://map.jacobsjo.eu](https://map.jacobsjo.eu) that is specifically made for this job.
