### ISSUE TITLE
Colors on map are messed up with enough ranges in temperate and humidity parametersrsrs

### ISSUE THREAD

**Issue by ApolloDatapacks** [jacobsjo/snowcapped#5]
Here's a comparison between the default biome layout and the biome layout with more temperature and humidity parameter ranges.
![image](https://user-images.githubusercontent.com/102649729/185067475-7e86d678-d80a-40b9-824b-80abe780d834.png)
![image](https://user-images.githubusercontent.com/102649729/185067615-f9cc78ed-6101-4fcb-8339-49761d8c339a.png)
This folder has the file I used to get this issue
[in-progress.snowcapped.zip](https://github.com/jacobsjo/snowcapped/files/9357669/in-progress.snowcapped.zip)

**Comment by ApolloDatapacks** [comment]
I got around to doing some more testing, it appears that the issue only occurs when there are more than 20 temperature intervals.

**Comment by jacobsjo** [comment]
fixed in #12
