### ISSUE TITLE
Y values on the editor appear to not match the real values in the generated world. 

### ISSUE THREAD

**Issue by WilliamWythers** [jacobsjo/snowcapped#6]
~~Sea level on the offset spline editor appears to consistently be set to around 4 blocks above sea level (y62) in the real world. Setting land to the level of the blue line produces land around y66.~~ Y coordinates on the display map also display the terrain about 3-4 blocks lower than what really generates.

**Comment by jacobsjo** [comment]
This was 2 different issues. The spline editor won't be fixed as it will hopefully be replaced by something better in the near future, for the y display on the map, could you please recheck if this is still an issue?

**Comment by jacobsjo** [comment]
Closing this, please create a new issue if this is still an issue.
