### ISSUE TITLE
Add warning when exporting with debug values

### ISSUE THREAD

**Issue by dhyces** [jacobsjo/snowcapped#8]
[vanilla_aylyth.txt](https://github.com/jacobsjo/snowcapped/files/9609593/vanilla_aylyth.txt)

Here's the saved json for the data in the 1.19.1 format. when using "export as datapack" and opening the dimension file "aylyth", every biome parameter has a continentalness of -1.2 to 1.0

**Comment by jacobsjo** [comment]
I should probably add a warning for that...

**Comment by jacobsjo** [comment]
debug options no longer exist, #12
